### ISSUE TITLE
Problem in the draw path

### ISSUE THREAD

**Issue by bernardotepedino** [cosbidev/PyTrack#4] opened 2022-10-05 15:49 UTC
I am having this problem in the last part of the code, when it was supposed to draw the map, does anyone know what could be?
![image](https://user-images.githubusercontent.com/61840631/194104315-826b76ef-2f88-4e43-8b63-7117bc0d9642.png)

Also, when I run the viterbi_search, I receive some messages such as: 

![image](https://user-images.githubusercontent.com/61840631/194104681-e48d81a5-0642-4e3b-8d4f-533be7be4f14.png)

Is this the reason for the error when drawing the map?

Thank you

**Comment by mtortora-ai** [comment] 2022-10-06 07:10
Please report the version of your environment (Python and PyTrack) for reproducibility.
Provide also a minimal example (with data), which can be copied, so that you can get better help and we can add a warning in future versions of the library.
However, the problem seems to be due to the output of `viterbi_search`. You can try increasing the radius value in the `candidate.get_candidates` function.

**Comment by bernardotepedino** [comment] 2022-10-06 15:43
Hi! My python version is 3.8.5 and my PyTrack is 2.0.4. the latest one.

Here I put an example of the points list that gives me this error. However, It works if you exclude the last item from the list.

[points.txt](https://github.com/cosbidev/PyTrack/files/9726414/points.txt)

I don't know why this error is happening. I already tried to change the radius and the linterp_dist at get_candidates.

Thanks for your help!

**Comment by mtortora-ai** [comment] 2022-10-19 10:51
A new version is out now, let me know if you have any problems with it.

**Comment by mtortora-ai** [comment] 2022-10-22 10:43
With version v2.0.6 of PyTrack, the problem is completely solved, without any errors. I tested the _points.txt_ dataset and the process appears fine. So I am going to close the issue as resolved.

**Closed** 2022-10-22 10:43 UTC
Labels: bug
